title: A Guide to Git for Student Projects
description: A website guide to using git for beginners, especially students working on projects or in groups for the first time. Made for an ENG331 assignment in Spring '25.
theme: just-the-docs

url: https://sophia-nunez/guide-to-git
back_to_top: true
back_to_top_text: "Back to top"

defaults:
- scope:
    path: ""
    type: "pages"
  values:
    layout: home

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
