title: A Guide to Git for Student Projects
description: A website guide to using git for beginners, especially students working on projects or in groups for the first time. Made for an ENG331 assignment in Spring '25.
theme: just-the-docs

url: https://guide-to-git.github.io/students-guide-to-git
back_to_top: true
back_to_top_text: "Back to top"
